name: Cache test

on: push

jobs:



  cache-create:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./test-folder

    steps:
      - uses: actions/checkout@v3
      
      - name: Create test file
        run: echo -e "This will be the text in the file \n this is the new line" >> file.txt 

      - name: Move file to artifacts folder
        run: |
          mkdir ubuntu-artifacts
          mv ./file.txt ./ubuntu-artifacts
          ls -lha

      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: ./test-folder/ubuntu-artifacts
          key: ubuntu-artifacts-cache


  cache-use:
    needs: cache-create
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Restore Ubuntu artifacts
        uses: actions/cache@v3
        with:
          path: ./test-folder/ubuntu-artifacts
          key: ubuntu-artifacts-cache

      - name: Check files
        run: |
          ls -lha
          echo "_____________"
          echo "_____________"
          echo "_____________"
          ls -lha ./test-folder/
          echo "_____________"
          echo "_____________"
          echo "_____________"
          ls -lha ./test-folder/ubuntu-artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Test release
          files: |
            ./test-folder/ubuntu-artifacts/*
