name: Master and Master PR test

on:
  pull_request:
  push:
    branches: master

jobs:
  build:
    if: ${{ github.base_ref == "master" }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Hello
        run: echo "Hello!!!"
