name: Run on Tag test

on:
  push:
    tags:        
      - '*' 

jobs:
  tag-test:
    runs-on: ubuntu-latest
  
    steps:    
      - name: Hello
        run: echo "Hello!!!!!!"
      
      - name: Get tag value
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Show tag value
        run: echo tag is $TAG
