name: Windows tests

on: push

jobs:
  zip-test-script:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run script
        shell: pwsh
        run: ./.github/scripts/windows/zip-test.ps1
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Test release name
          files: |
            info.json
            archive.zip