name: Windows tests

on: push

jobs:
  zip-test-script:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        shell: pwsh
        run: ./.github/scripts/windows/zip-test.ps1
